import { $, state, CHORDS, DIATONIC_ST, DEGREE_SEMITONES, SOLFEGE, PART_RANGES } from './state.js';
import { midiToFreq, degreeForMidi, intervalName } from './util.js';
import { ensureAudio, startDrone, stopDrone } from './audio.js';
export function setDisplay(midis,label){ state.display.midis = midis.slice(); state.display.label = label||''; const txt = label || (midis.length? `${midis.length} tone(s)` : '—'); const nb=$('nowBadge'); if(nb) nb.textContent = txt; }
export function currentDroneFreqs(){ return state.droneSemis.map(semi=>midiToFreq(state.doMidi + state.chordRootSemi + semi, state.a4)); }
export function pickRandomMidiInRange(){ return Math.floor(state.minMidi + Math.random()*(state.maxMidi-state.minMidi+1)); }
export function playTones(midis, dur=1.5, label=''){ setDisplay(midis,label); const freqs=midis.map(m=>midiToFreq(m, state.a4)); startDrone(freqs); state.droneOn=true; setTimeout(()=>{ stopDrone(); state.droneOn=false; }, dur*1000); }
export function onScaleFilter(mid){ if(!state.onScaleOnly) return true; return degreeForMidi(mid, state.doMidi)!=null; }
export function hiddenCluster(n){ const root=state.doMidi; const pool=[0,2,4,5,7,9,11].flatMap(semi=>{ let base=root+semi; const list=[]; for(let o=-2;o<=3;o++){ const mm=base+12*o; if(mm>=state.minMidi&&mm<=state.maxMidi) list.push(mm);} return list;});
  const opts=state.onScaleOnly? pool : (()=>{ const arr=[]; for(let m=state.minMidi;m<=state.maxMidi;m++) arr.push(m); return arr; })();
  const chosen=[]; while(chosen.length<n && opts.length){ const i=Math.floor(Math.random()*opts.length); const cand=opts.splice(i,1)[0]; if(onScaleFilter(cand)) chosen.push(cand);} state.hidden={midi:chosen.sort((a,b)=>a-b)}; $('hiddenBadge').textContent=`${n} tones ready`; playTones(chosen,2.5,`Hidden cluster (${n})`);
}
export function doInterval(){ const dir=$('intervalDir').value; const min=Number($('intervalMin').value), max=Number($('intervalMax').value); let a=pickRandomMidiInRange(); let span; const spans=[]; for(let s=min;s<=max;s++){ if(!state.onScaleOnly||DIATONIC_ST.has(s)) spans.push(s);} if(!spans.length) spans.push(min); span=spans[Math.floor(Math.random()*spans.length)]; let upDown=dir==='either'?(Math.random()<0.5?-1:1):(dir==='down'?-1:1); let b=a+upDown*span; if(b<state.minMidi||b>state.maxMidi){ b=a - upDown*span; }
  if(state.onScaleOnly){ if(degreeForMidi(a,state.doMidi)==null) a=state.doMidi+DEGREE_SEMITONES[Math.floor(Math.random()*DEGREE_SEMITONES.length)]; if(degreeForMidi(b,state.doMidi)==null){ const d=DEGREE_SEMITONES[Math.floor(Math.random()*DEGREE_SEMITONES.length)]; b=state.doMidi+d; }}
  state.interval={a,b}; $('intervalBadge').textContent='?'; playTones([a],1.2,'Interval A'); setTimeout(()=>playTones([b],1.2,'Interval B'),1300);
}
export function revealInterval(){ if(!state.interval){ $('intervalBadge').textContent='—'; return;} const {a,b}=state.interval; const up=b>=a; const st=Math.abs(b-a)%12; const sA=SOLFEGE[degreeForMidi(a,state.doMidi)]; const sB=SOLFEGE[degreeForMidi(b,state.doMidi)]; const name=intervalName(st); $('intervalBadge').textContent=`${sA} → ${sB}  (${name}${up?' up':' down'})`; }
export function revealHidden(){ if(!state.hidden){ $('hiddenBadge').textContent='none'; return;} const sols=state.hidden.midi.map(m=>{ const d=degreeForMidi(m,state.doMidi); return d!=null? SOLFEGE[d] : '?'; }); const base=state.doMidi; const ints=state.hidden.midi.map(m=> intervalName(Math.abs(m-base)%12)).join(' · '); $('hiddenBadge').textContent=`${sols.join(', ')}  [${ints}]`; }
// chord qualities
export function chordQualityForMajorKey(degreeSemi){ const deg=((degreeSemi%12)+12)%12; return (deg===0||deg===5||deg===7)?'maj': (deg===2||deg===4||deg===9)?'min':'maj'; }
export function triadSemisForDegree(degreeSemi){ const q=chordQualityForMajorKey(degreeSemi); return q==='maj'?[0,4,7]:[0,3,7]; }
export function buildArpeggioSemis(degreeSemi){ const tri=triadSemisForDegree(degreeSemi); return [...tri, tri[1], tri[0]]; }
export function buildArpeggioSemisDesc(degreeSemi){ const tri=triadSemisForDegree(degreeSemi); return [tri[2], tri[1], tri[0], tri[1], tri[2]]; }
export function degreeToRoman(semi){ const idx=DEGREE_SEMITONES.indexOf(((semi%12)+12)%12); return ["I","II","III","IV","V","VI","VII"][idx]; }
export function parseProg(name){ if(name==='I-IV-V') return [0,5,7]; if(name==='I-vi-IV-V') return [0,9,5,7]; if(name==='ii-V-I') return [2,7,0]; return null; }
export function progressionFromUI(){ const preset=$('satbPreset').value; if(preset!=='custom'){ return parseProg(preset); } return [Number($('satbC1').value), Number($('satbC2').value), Number($('satbC3').value)]; }
export function nearestInRange(midis, range){ const mid=(range[0]+range[1])/2; let best=midis[0], bd=1e9; for(const m of midis){ const d=Math.abs(m-mid); if(d<bd && m>=range[0] && m<=range[1]){ bd=d; best=m; } } return best; }
export async function satbPlay(){ await ensureAudio(); const part=$('satbPart').value; const dur=Math.max(1, Math.min(8, Number($('satbDur').value)||2)); const prog=progressionFromUI(); const badge=$('satbBadge'); const range=PART_RANGES[part]; if(!prog){ badge.textContent='set custom steps'; return; }
  for(const rootSemi of prog){ const tri=[0,4,7].map(s=> state.doMidi + rootSemi + s); const target=nearestInRange(tri, range); state.targetSemi=(target-state.doMidi)%12; setDisplay(tri, `${degreeToRoman(rootSemi)} triad`); startDrone(tri.map(m=>midiToFreq(m, state.a4))); badge.textContent = `${degreeToRoman(rootSemi)} triad • aim ${(state.onScaleOnly?'':'')} `; await new Promise(r=>setTimeout(r, dur*1000)); stopDrone(); await new Promise(r=>setTimeout(r,150)); }
  badge.textContent='done'; setTimeout(()=>badge.textContent='—',1200);
}
// Warmup
export function labelForDegree(semi){ const map={0:'I',2:'ii',4:'iii',5:'IV',7:'V',9:'vi'}; return map[((semi%12)+12)%12]||'?'; }
export function buildWarmupPlan(){ const seq=[]; const scaleUp=[0,2,4,5,7,9,11,12].map(s=>state.doMidi+s); const scaleDown=[...scaleUp].reverse(); seq.push({label:'Major scale ↑', tones:scaleUp, step:0.6}); seq.push({label:'Major scale ↓', tones:scaleDown, step:0.6}); const aroundUp=[0,2,0,4,0,5,0,7,0,9,0,11,0,12].map(s=>state.doMidi+s); const aroundDown=[12,11,12,9,12,7,12,5,12,0].map(s=>state.doMidi+s); seq.push({label:'Intervals from Do ↑', tones:aroundUp, step:0.7}); seq.push({label:'Intervals from Do ↓', tones:aroundDown, step:0.7}); const degrees=[0,2,4,5,7,9]; const forward=degrees.map(d=>({label:`${labelForDegree(d)} arpeggio (↑)`, tones:buildArpeggioSemis(d).map(s=>state.doMidi+d+s), step:0.7})); const back=[...degrees].reverse().map(d=>({label:`${labelForDegree(d)} arpeggio (↓)`, tones:buildArpeggioSemisDesc(d).map(s=>state.doMidi+d+s), step:0.7})); return [...seq, ...forward, ...back]; }
export async function warmUp(){ await ensureAudio(); const badge=$('warmupBadge'); const plan=buildWarmupPlan(); for(const part of plan){ if(part.label) badge.textContent=part.label; for(const n of part.tones){ setDisplay([n], part.label); startDrone([midiToFreq(n,state.a4)]); await new Promise(r=>setTimeout(r, part.step*1000)); stopDrone(); await new Promise(r=>setTimeout(r,120)); } } badge.textContent='done'; setTimeout(()=>badge.textContent='—',1500); }
