import { $, state, SOLFEGE } from './state.js';
import { buildScalePitches, freqToMidi, midiToFreq, centsBetween } from './util.js';
import { pdState } from './pitch.js';
export const canvas = $('#staff');
const ctx = canvas.getContext('2d');
export function roundedRect(x,y,w,h,r,fill,stroke){ ctx.beginPath(); ctx.moveTo(x+r,y); ctx.arcTo(x+w,y,x+w,y+h,r); ctx.arcTo(x+w,y+h,x,y+h,r); ctx.arcTo(x,y+h,x,y,r); ctx.arcTo(x,y,x+w,y,r); if(fill) ctx.fill(); if(stroke) ctx.stroke(); }
export function drawShapeBadge(x,y,sol){ const colors={Do:'#8bd3ff',Re:'#a7f3d0',Mi:'#fde68a',Fa:'#fca5a5',Sol:'#c4b5fd',La:'#f9a8d4',Ti:'#fdba74'}; ctx.save(); ctx.strokeStyle='#2a3051'; ctx.fillStyle='#12182a'; roundedRect(x-6,y-6,48,16,8,true,true); ctx.fillStyle=colors[sol]||'#9ab'; if(sol==='La'){ ctx.fillRect(x+2, y-2, 8, 8);} else if(sol==='Ti'){ ctx.beginPath(); ctx.arc(x+6, y+2, 4, 0, Math.PI*2); ctx.fill(); ctx.beginPath(); ctx.moveTo(x+6, y+6); ctx.lineTo(x+2, y-2); ctx.lineTo(x+10, y-2); ctx.closePath(); ctx.fill(); } else if(sol==='Do'){ ctx.beginPath(); ctx.moveTo(x+6, y-2); ctx.lineTo(x+2, y+6); ctx.lineTo(x+10, y+6); ctx.closePath(); ctx.fill(); } else if(sol==='Re'){ ctx.beginPath(); ctx.ellipse(x+6,y+2,4,5,0,0,Math.PI*2); ctx.fill(); } else if(sol==='Mi'){ ctx.save(); ctx.translate(x+6,y+2); ctx.rotate(Math.PI/4); ctx.fillRect(-4,-4,8,8); ctx.restore(); } else if(sol==='Fa'){ ctx.fillRect(x+2,y-2,8,8); } else if(sol==='Sol'){ ctx.beginPath(); ctx.ellipse(x+6,y+2,5,3,0,0,Math.PI*2); ctx.fill(); } ctx.fillStyle='#cfe6ff'; ctx.font='12px system-ui'; ctx.textAlign='left'; ctx.fillText(sol, x+20, y+6); ctx.restore(); }
export function resizeCanvas(){ const dpr=window.devicePixelRatio||1; const w=canvas.clientWidth; const h=canvas.clientHeight; canvas.width=Math.floor(w*dpr); canvas.height=Math.floor(h*dpr); ctx.setTransform(dpr,0,0,dpr,0,0); }
export function drawStaff(){ resizeCanvas(); const w=canvas.clientWidth, h=canvas.clientHeight; ctx.clearRect(0,0,w,h); const spacing = 16*state.zoom; const marginX=16; const top=h*0.18; ctx.strokeStyle="#233056"; ctx.lineWidth=1.4; for(let i=0;i<5;i++){ const y=top+i*spacing; ctx.beginPath(); ctx.moveTo(marginX,y); ctx.lineTo(w-marginX,y); ctx.stroke(); }
const range = state.maxMidi - state.minMidi; const usableH = h*0.62*state.zoom; const baseY = top + spacing*2.0; function yForMidi(m){ const t=(m - state.minMidi)/range; return baseY + (0.5 - t)*usableH; }
const scale = buildScalePitches(state.doMidi, state.minMidi, state.maxMidi); ctx.fillStyle="#8ba3c6"; ctx.font="12px system-ui"; ctx.textAlign="left"; scale.forEach((p)=>{ const y=yForMidi(p.midi); ctx.save(); ctx.globalAlpha=0.16; ctx.beginPath(); ctx.moveTo(56,y); ctx.lineTo(w-16,y); ctx.stroke(); ctx.restore(); drawShapeBadge(20,y-8,p.sol); });
// drones
const drones = currentDroneFreqs(); drones.forEach(f=>{ const m = Math.round(freqToMidi(f, state.a4)); const y=yForMidi(m); ctx.fillStyle="#1a2740"; ctx.strokeStyle="#8bd3ff"; ctx.lineWidth=2; roundedRect(160,y-8,22,16,6,true,true); ctx.fillStyle="#9bdcff"; ctx.fillText(f.toFixed(1)+" Hz", 188, y+4); });
// aim (target)
const tm = state.doMidi + state.chordRootSemi + state.targetSemi; const ty = yForMidi(tm); ctx.strokeStyle="#34d399"; ctx.setLineDash([10,6]); ctx.lineWidth=2.4; ctx.beginPath(); ctx.moveTo(marginX, ty); ctx.lineTo(w-marginX, ty); ctx.stroke(); ctx.setLineDash([]); ctx.fillStyle="#34d399"; ctx.fillText("AIM", w-52, ty-6);
// active exercise notes overlay
if(state.display.midis && state.display.midis.length){ const mids = state.display.midis; ctx.save(); ctx.lineWidth=2; mids.forEach((m,i)=>{ const y=yForMidi(m); ctx.fillStyle="#7dd3fc"; ctx.strokeStyle="#0b0f19"; ctx.beginPath(); ctx.arc(100+i*14,y,6,0,Math.PI*2); ctx.fill(); ctx.stroke(); }); ctx.restore(); }
// mic dot
const micHz = pdState.hz; $("micHz").textContent = micHz? micHz.toFixed(1): "—"; if(micHz){ const micMidi=freqToMidi(micHz, state.a4); const y=yForMidi(micMidi); const targetFreq=midiToFreq(tm, state.a4); const delta=centsBetween(micHz, targetFreq); $("micCents").textContent=(delta>0?"+":"")+delta.toFixed(1); const ad=Math.abs(delta); let col = ad<state.tolerance?"#34d399": ad<state.tolerance*2?"#fbbf24":"#f87171"; ctx.fillStyle=col; ctx.strokeStyle="#0b0f19"; ctx.beginPath(); ctx.arc(w-40,y,7,0,Math.PI*2); ctx.fill(); ctx.stroke(); }
}
