import { $, state, SOLFEGE, DEGREE_SEMITONES, CHORDS } from './state.js';
import { midiName } from './util.js';
import { beepTarget } from './audio.js';
export function buildNoteMenus(){ const doSel=$('doNote'), minSel=$('minNote'), maxSel=$('maxNote'); doSel.innerHTML=''; minSel.innerHTML=''; maxSel.innerHTML=''; for(let m=36;m<=84;m++){ const opt1=new Option(midiName(m),m); const opt2=new Option(midiName(m),m); const opt3=new Option(midiName(m),m); if(m===state.doMidi) opt1.selected=true; if(m===state.minMidi) opt2.selected=true; if(m===state.maxMidi) opt3.selected=true; doSel.add(opt1); minSel.add(opt2); maxSel.add(opt3);} }
export function buildRootMenu(){ const rootSel=$('chordRoot'); rootSel.innerHTML=''; [0,2,4,5,7,9,11].forEach((semi,i)=>{ const roman=["I","II","III","IV","V","VI","VII"][i]; const opt=new Option(`${SOLFEGE[i]} (${roman})`, semi); if(semi===state.chordRootSemi) opt.selected=true; rootSel.add(opt); }); }
export function buildChordMenus(){ const chordSel=$('chordSelect'); chordSel.innerHTML=''; Object.keys(CHORDS).forEach(name=>{ const opt=new Option(name,name); if(name===state.chord) opt.selected=true; chordSel.add(opt); }); }
export function buildChordButtons(onChange){ const row=$('chordQuick'); row.innerHTML=''; Object.keys(CHORDS).forEach(name=>{ const btn=document.createElement('button'); btn.textContent=name; btn.onclick=()=>{ onChange(name);}; row.appendChild(btn); }); }
export function renderDroneDegreeButtons(onToggle){ const host=$('droneNotes'); host.innerHTML=''; const used=new Set(state.droneSemis); [0,2,4,5,7,9,11].forEach(semi=>{ const idx=DEGREE_SEMITONES.indexOf(semi); const label=SOLFEGE[idx]; const btn=document.createElement('button'); btn.innerHTML=`<span class="shape ${label.toLowerCase()}"></span> ${label}`; btn.onclick=()=>{ if(used.has(semi)) used.delete(semi); else used.add(semi); onToggle(Array.from(used).sort((a,b)=>a-b)); }; if(used.has(semi)) btn.classList.add('primary'); host.appendChild(btn); }); }
export function renderTargetButtons(){ const row=$('targetRow'); row.innerHTML=''; state.droneSemis.forEach(semi=>{ const idx=DEGREE_SEMITONES.indexOf(semi); const label=SOLFEGE[idx]; const b=document.createElement('button'); b.innerHTML=`<span class="shape ${label.toLowerCase()}"></span> Aim: ${label}`; b.onclick=()=>{ state.targetSemi=semi; updateTargetLabel(); if(state.playAim){ beepTarget(); } }; if(semi===state.targetSemi) b.classList.add('good'); row.appendChild(b); }); updateTargetLabel(); }
export function updateTargetLabel(){ const idx=DEGREE_SEMITONES.indexOf(state.targetSemi); const label=idx>=0? SOLFEGE[idx] : '(none)'; $('targetLabel').textContent=label; }
export function switchTab(tab){ state.currentTab=tab; ["free","cluster","intervals","satb","theory"].forEach(t=>{ const btn=[...document.querySelectorAll('.tab')].find(b=>b.dataset.tab===t); if(btn) btn.classList.toggle('active', t===tab); $('panel-'+t).style.display = t===tab? 'block':'none'; }); }
export function handleGlobalKey(e){ const el=document.activeElement; const isEditable = el && (el.tagName==='INPUT' || el.tagName==='TEXTAREA' || el.isContentEditable || el.tagName==='SELECT'); if(isEditable) return; const k=(e && typeof e.key==='string')? e.key.toLowerCase():''; if(k==='m'){ const evt=new CustomEvent('app:toggleMic'); window.dispatchEvent(evt);} }
